"""Add is_active field to Client and VisitReport models

Revision ID: 1dcdbe1bfc91
Revises: 70d39b4bb819
Create Date: 2025-09-29 06:51:40.715556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcdbe1bfc91'
down_revision = '70d39b4bb819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('visit_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_reports', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
