"""Add address to Client

Revision ID: 21bf2170a3c1
Revises: 1dcdbe1bfc91
Create Date: 2025-09-29 20:47:39.727779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bf2170a3c1'
down_revision = '1dcdbe1bfc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
