"""Add salesman_name field to Client model

Revision ID: 70d39b4bb819
Revises: 
Create Date: 2025-09-29 06:19:21.864762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d39b4bb819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesman_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('category')
        batch_op.drop_column('is_active')
        batch_op.drop_column('description')
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('barcode')
        batch_op.drop_column('weight')
        batch_op.drop_column('min_stock_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_stock_level', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('salesman_name')

    # ### end Alembic commands ###
